### ISSUE TITLE
Question about shave

### ISSUE THREAD

**Issue by ExpectoPatronumCG** [nmhkahn/CARN-pytorch#18]
why you add the shave when you calculate the psnr?

h_chop, w_chop = h_half + cfg.shave, w_half + cfg.shave

I hope to get your answer.thx

**Comment by nmhkahn** [comment]
The shave is used when splitting the input image into patches to avoid OOM if the input image size is big.
If shave is zero, means splitting the image without an overlap, then the boundary of each patch can be distorted so that we add shave parameter in there.
But after producing the SR image, we perform the inverse-split operation so that shave parameter doesn't harm the overall SR image.

**Comment by ExpectoPatronumCG** [comment]
> The shave is used when splitting the input image into patches to avoid OOM if the input image size is big.
> If shave is zero, means splitting the image without an overlap, then the boundary of each patch can be distorted so that we add shave parameter in there.
> But after producing the SR image, we perform the inverse-split operation so that shave parameter doesn't harm the overall SR image.

thanks. I still have a question about what is the super resolution factor（SRF） for calculating PSNR in matlab code that you provided in another issue.
I guess it means x2 x3 x4. But I don't find the sure answer.

**Comment by nmhkahn** [comment]
For a fair benchmark with conventional algorithms, many literatures extract the borderline pixels when they calculate the PSNR, and we follow the protocol as well.
But note that, the benchmark results have to be calculated by the Matlab since there some differences exist between the python and Matlab when you convert the RGB to a grayscale image.
