### ISSUE TITLE
The image size of reconstruction result from Urban100 don't match with original images.

### ISSUE THREAD

**Issue by qibao77** [nmhkahn/CARN-pytorch#2]
The original image resolution of Urban100 exceeds 1024p, but your results are less than it.

**Comment by nmhkahn** [comment]
Hi.
Thanks for letting us know the problem. Perhaps there was some undesirable thing happens when we did create LR image in x2 and x3 scale. So the HR resolution of x2 and x3 scale was incorrect compared to the original dataset, thus leads the different resolution of the reconstruction image.

Honestly, when we benchmark on the Urban x3 dataset, it seems weird that the PSNR score of our model was unbelievably low, but now it's quite reasonable.
Anyway, here is the new result table:
<img src="https://user-images.githubusercontent.com/16869368/43751248-0c4bc946-9a37-11e8-9776-6daea5bb92f9.png">

**Comment by qibao77** [comment]
Thank you for your answer. But I have another problem. The parameters of CARN or CARN-M should be different on three scale factors since you are upsampling LR images at the end of the network, but params. of CARN or CARN-M are same in your table (1592K and 412K).

**Comment by nmhkahn** [comment]
The reason is because the model holds all the upsample blocks even they doesn't use it. This idea also be used in MDSR to implement multi-scale learning. And we also claim that this property makes the model more efficient since we can process multiple scale data only using single model.

If you want more details, please check paragraph 4 in section 4.3 in our [paper](https://arxiv.org/pdf/1803.08664.pdf).

**Comment by qibao77** [comment]
I find it, thank you very much!

**Comment by kk6398** [comment]
Hello，dear owner：
         I have two questions that confuse me a lot , it still puzzles me after I have searched much on the internet.
         for 1) ,I have read the answer above , I still don't know the exact reason why the number of parameters is 1592K and 412K constantly. I run the program on my computer, when I change the scale for X2, X3, X4(group = 1) , the parameters are 964187,1148827, 1111899, respectively. I only get the parameters----1592K when scale = 0.
        for 2),I puzzle that how to get or calculate  the size of model----Mutil-Adds.  It seems like that it don't symbolize in the program.
        
        Waiting for your answer sincerely.
