### ISSUE TITLE
 multi-scale  training and single scale training

### ISSUE THREAD

**Issue by yiyunchen** [nmhkahn/CARN-pytorch#21]
is the single training can achived a better result than multi scale?
and I do the multi scale training, but i think when 6×105 steps, the PSNR is still increasing?
I would like to know the setting mentioned in the paper is for single training or multi scale training?
i am a rookie.
thank you!

**Comment by nmhkahn** [comment]
Hi.
We apply a multi-scale training manner for 6x10^5 steps with settings described in the readme.
Normally, for low-resolution cases such as x3 and x4, multi-scale shows better performances, while sometimes single-scale has advantages on the x2.
I believe that it because the model sees only the 1/3 of x2 scale training data so if you train the model longer then this problem can be alleviated.

**Comment by yiyunchen** [comment]
thank you!
