### ISSUE TITLE
Split into sub images(path) for inference?

### ISSUE THREAD

**Issue by idealboy** [nmhkahn/CARN-pytorch#25]
Sir,

When I test DIV2K, I think it is a valid way to split path ,and run SR for each patch independently.

otherwise, it will be out of memory.

my question is that, is this a common using way in SR area? will it cause some artifact like vertical or horizon line?

thank you very much,sir!

**Comment by nmhkahn** [comment]
If possible it's the best way to input the full image but because the OOM error many models split input images. In this case, boundary artifact can occur as you say. So to minimize such risk, when split the image, make the patches larger than your desired output and remove the excess space when merging back the restored output. See the `shave` arguments.

**Comment by idealboy** [comment]
> If possible it's the best way to input the full image but because the OOM error many models split input images. In this case, boundary artifact can occur as you say. So to minimize such risk, when split the image, make the patches larger than your desired output and remove the excess space when merging back the restored output. See the `shave` arguments.

yes, sir, I just do like this, I just split the whole image into sixteen part when processing 4K super resolution, with shave is 20.

thank you, and I will debug whether the artifact occur, and then adjust the shave value.
