### ISSUE TITLE
Multi-scale Training

### ISSUE THREAD

**Issue by uyekt** [nmhkahn/CARN-pytorch#7]
Hi,

In your solver I found following comment about the multiscale training. 
` # only use one of multi-scale data`

So you switch randomly between the scale, correct? Can you elaborate what would be a better idea?

Thx a lot for sharing your code!

**Comment by nmhkahn** [comment]
Yes, you're right. In the dataset.py, it returns all possible scales, x2 to x4 and randomly choose among of them in solver.py.

The meaning of "better idea" was not randomly choose scale in solver, but in dataset. So to make minimize of the data loading cost.

But, because all the data is loaded on the memory first, it may not be the bottleneck.
